FotoBox: FotoBox::FotoBox Class Reference
FotoBox::FotoBox Class Reference
The FotoBox class Main class to control UI and controll the process.
#include <fotobox.h>
Signals
void start ()
signal: start FotoBox
void startBuzzer ()
signal: start query pin with Buzzer class
Public Member Functions
FotoBox (QWidget *parent=nullptr)
FotoBox constructor.
~FotoBox () override
FotoBox destructor.
FotoBox (const FotoBox &other)=delete
FotoBox default copy constructor.
FotoBox & operator= (const FotoBox &other)=delete
FotoBox default copy assignment.
FotoBox (FotoBox &&other)=delete
FotoBox default move constructor.
FotoBox & operator= (FotoBox &&other)=delete
FotoBox default move assignment.
Private Slots
void photo ()
trigger camera to shot a photo and try to show it
void preferenceDialog ()
show preference dialog and close dialog
Private Member Functions
void closeFullscreenWindowOnMac ()
Is used as a workaround for macOS to close a fullscreen window.
void keyPressEvent (QKeyEvent *event) override
filter key press events
void mouseReleaseEvent (QMouseEvent *event) override
This event handler, for event event, can be reimplemented in a subclass to receive mouse release events for the widget.
void buttons ()
With or without buttons.
void countdown ()
With or without countdown.
void buzzer ()
creates a new Buzzer object
void loadPhoto (const QString &i_filePath)
try to load the photo to QPixmap
void drawText (const QString &i_text)
Draw text on the QPixmap.
Static Private Member Functions
static auto calculateFontSize (double i_width, double i_widthFont) -> double
calculate "maximum" fitting font size
Private Attributes
Ui::FotoBoxDialog * m_ui
Countdown m_countdown
QThread m_workerThread
Buzzer m_buzzer
Camera m_camera
QPixmap m_photo
const QString m_photoDir
const std::vector< Qt::Key > m_triggerKey {Qt::Key_N, Qt::Key_Return, Qt::Key_Enter, Qt::Key_PageDown, Qt::Key_PageUp, Qt::Key_Left, Qt::Key_Right, Qt::Key_Up, Qt::Key_Down, Qt::Key_Space, Qt::Key_Backspace}
const std::vector< Qt::Key > m_preferenceKey {Qt::Key_P, Qt::Key_S, Qt::Key_E}
const std::vector< Qt::Key > m_quitKey {Qt::Key_Escape, Qt::Key_Q}
Static Private Attributes
static constexpr int STATUSBAR_MSG_TIMEOUT = 8000
static constexpr double COMPARE = 1.25
Detailed Description
The FotoBox class Main class to control UI and controll the process.
Definition at line 30 of file fotobox.h.
Constructor & Destructor Documentation
FotoBox() [1/3]
FotoBox::FotoBox::FotoBox (QWidget * parent = nullptr) explicit
FotoBox constructor.
Parameters
parent QWidget
Definition at line 21 of file fotobox.cpp.
     : QDialog(parent)
     , m_ui(new Ui::FotoBoxDialog)
     , m_countdown(this)
     , m_workerThread(this)
     , m_camera(this)
     , m_photoDir(PreferenceProvider::instance().photoFolder() + QDir::separator())
 {
     //setup GUI
     m_ui->setupUi(this);
     //e.g. 'FotoBox v1.2.3 (Copyright 2016 Thomas Kais)'
     setWindowTitle(QStringLiteral("%1 v%2 (Copyright 2016 %3)").arg(QApplication::applicationName(), QApplication::applicationVersion(), QApplication::organizationName()));
     //set Background Color
     setStyleSheet(QStringLiteral("#FotoBoxDialog { background-color:%1; }").arg(PreferenceProvider::instance().backgroundColor()));
     //delete everything on close
     setAttribute(Qt::WA_DeleteOnClose);
     //show QStatusBar only when needed (safe space for the photos)
     connect(m_ui->statusBar, &QStatusBar::messageChanged, this, [&](const QString &i_message) { i_message.isNull() ? m_ui->statusBar->hide() : m_ui->statusBar->show(); });
     //hide status bar (ATTENTION: don't use at other places, see connect line above)
     m_ui->statusBar->hide();
     //with or without buttons?
     buttons();
     //Buzzer class (Raspberry Pi GPIO using pigpio)
 #if defined(BUZZER_AVAILABLE)
     if (PreferenceProvider::instance().queryInterval() > 0) {
         buzzer();
     }
 #endif
     //countdown?
     countdown();
 }
References FotoBox::PreferenceProvider::instance().
~FotoBox()
FotoBox::FotoBox::~FotoBox () override
FotoBox destructor.
Definition at line 135 of file fotobox.cpp.
 {
 #if defined(BUZZER_AVAILABLE)
     if (PreferenceProvider::instance().queryInterval() > 0) {
         //stop query pin
         m_buzzer.stop();
     }
 #endif
     //terminate and delete Buzzer thread
     m_workerThread.quit();
     m_workerThread.wait();
     delete m_ui;
 }
References FotoBox::PreferenceProvider::instance().
FotoBox() [2/3]
FotoBox::FotoBox::FotoBox (const FotoBox & other) delete
FotoBox default copy constructor.
FotoBox() [3/3]
FotoBox::FotoBox::FotoBox (FotoBox && other) delete
FotoBox default move constructor.
Member Function Documentation
buttons()
void FotoBox::FotoBox::buttons () private
With or without buttons.
Definition at line 60 of file fotobox.cpp.
 {
     if (PreferenceProvider::instance().showButtons()) {
         //connect buttons
         connect(m_ui->btnStart, &QPushButton::clicked, this, &FotoBox::start);
         connect(m_ui->btnPreferencesDialog, &QPushButton::clicked, this, &FotoBox::preferenceDialog);
         connect(m_ui->btnQuitApp, &QPushButton::clicked, QCoreApplication::instance(), &QCoreApplication::quit);
     } else {
         //hide mouse cursor
         QGuiApplication::setOverrideCursor(Qt::BlankCursor);
         //hide buttons
         m_ui->btnStart->hide();
         m_ui->btnPreferencesDialog->hide();
         m_ui->btnQuitApp->hide();
     }
 }
References FotoBox::PreferenceProvider::instance().
buzzer()
void FotoBox::FotoBox::buzzer () private
creates a new Buzzer object
Definition at line 77 of file fotobox.cpp.
 {
 #if defined(BUZZER_AVAILABLE)
     if (m_workerThread.isRunning()) {
         return;
     }
     if (!m_buzzer.initialise()) {
         //pigpio init not successfull
         m_ui->statusBar->showMessage(tr("Buzzer isn't working. Please check 'pigpio' deamon."), STATUSBAR_MSG_TIMEOUT);
         return;
     }
     //move to a thread
     m_buzzer.moveToThread(&m_workerThread);
     //connect the start signal for buzzer
     connect(this, &FotoBox::startBuzzer, &m_buzzer, &Buzzer::queryPin);
     //start fotobox if buzzer was triggered
     connect(&m_buzzer, &Buzzer::triggered, this, &FotoBox::start);
     m_workerThread.start();
     //start query
     emit startBuzzer();
 #endif
 }
References FotoBox::Buzzer::queryPin(), and FotoBox::Buzzer::triggered().
calculateFontSize()
auto FotoBox::FotoBox::calculateFontSize (double i_width, double i_widthFont) -> double static private
calculate "maximum" fitting font size
Parameters
i_width double
i_widthFont double
Returns
best fitting fontsize
Definition at line 280 of file fotobox.cpp.
 {
     auto factor = i_width / i_widthFont;
     if ((factor < 1) || (factor > COMPARE)) {
         return factor;
     }
     return 0.0;
 }
closeFullscreenWindowOnMac()
void FotoBox::FotoBox::closeFullscreenWindowOnMac () private
Is used as a workaround for macOS to close a fullscreen window.
close the window again, using the native MacOS API (https://bugreports.qt.io/browse/QTBUG-46701)
Definition at line 16 of file fotoboxmac.mm.
 {
     //WORKAROUND QTBUG-36714: closing a full screen QMainWindow leaves the screen black on macOS if there are multiple instances of QMainWindow created
     const auto *view = reinterpret_cast<NSView *>(winId());
     if (view == nil) {
         return;
     }
     const auto *window = view.window;
     if (window == nil) {
         return;
     }
     //close the window again, using the native MacOS API
     [window close];
 }
countdown()
void FotoBox::FotoBox::countdown () private
With or without countdown.
Definition at line 106 of file fotobox.cpp.
 {
     //initialize countdown
     m_ui->lcdCountdown->hide();
     if (PreferenceProvider::instance().countdown() > 0) {
         //add countdown
         m_countdown.setStartTime(static_cast<unsigned int>(PreferenceProvider::instance().countdown()));
         connect(this, &FotoBox::start, &m_countdown, &Countdown::start);
         connect(&m_countdown, &Countdown::elapsed, this, &FotoBox::photo);
         //update UI
         connect(&m_countdown, &Countdown::update, this, [&](const unsigned int i_timeLeft) {
             //hide photo and show countdown
             m_ui->lblPhoto->hide();
             m_ui->lcdCountdown->show();
             m_ui->lcdCountdown->display(QString::number(i_timeLeft));
         });
         //apply font color
         auto palette = m_ui->lcdCountdown->palette();
         palette.setColor(QPalette::WindowText, PreferenceProvider::instance().countdownColor());
         m_ui->lcdCountdown->setPalette(palette);
     } else {
         //disable countdown
         connect(this, &FotoBox::start, this, &FotoBox::photo);
     }
 }
References FotoBox::Countdown::elapsed(), FotoBox::PreferenceProvider::instance(), FotoBox::Countdown::start(), and FotoBox::Countdown::update().
drawText()
void FotoBox::FotoBox::drawText (const QString & i_text) private
Draw text on the QPixmap.
See also
m_photo
Parameters
i_text text to write
Definition at line 260 of file fotobox.cpp.
 {
     //painter begins painting the paint device immediately!
     QPainter painter(&m_photo);
     //set color and font
     painter.setPen(QPen(PreferenceProvider::instance().backgroundColor()));
     //calculate best font size
     QFont font = painter.font();
     const auto size = calculateFontSize(m_photo.rect().width(), painter.fontMetrics().boundingRect(i_text).width());
     font.setPointSizeF(font.pointSizeF() * size);
     painter.setFont(font);
     //draw text on image
     painter.drawText(m_photo.rect(), Qt::AlignCenter, i_text);
     m_ui->lblPhoto->setPixmap(m_photo);
 }
References FotoBox::PreferenceProvider::instance().
keyPressEvent()
void FotoBox::FotoBox::keyPressEvent (QKeyEvent * event) override private
filter key press events
Enter -> take a photo / Escape -> quit application
Parameters
event QKeyEvent
Definition at line 151 of file fotobox.cpp.
 {
     //prevent triggering method too often
     if (!event->isAutoRepeat()) {
         //start FotoBox
         if (std::any_of(m_triggerKey.cbegin(), m_triggerKey.cend(), [&](const Qt::Key i_key) -> bool { return event->key() == i_key; })) {
             Q_EMIT start();
             return;
         }
         //preferences dialog
         if (std::any_of(m_preferenceKey.cbegin(), m_preferenceKey.cend(), [&](const Qt::Key i_key) -> bool { return event->key() == i_key; })) {
             preferenceDialog();
             return;
         }
         //quit application
         if (std::any_of(m_quitKey.cbegin(), m_quitKey.cend(), [&](const Qt::Key i_key) -> bool { return event->key() == i_key; })) {
             if (event->modifiers() == Qt::ShiftModifier) {
                 QCoreApplication::quit();
             }
             m_ui->statusBar->showMessage(tr("To quit the application, please hold down the Shift key while press Escape key."), STATUSBAR_MSG_TIMEOUT);
             return;
         }
     }
 }
loadPhoto()
void FotoBox::FotoBox::loadPhoto (const QString & i_filePath) private
try to load the photo to QPixmap
Parameters
i_filePath path to photo
Definition at line 238 of file fotobox.cpp.
 {
     //try to load the photo shot by camera
     if (m_photo.load(i_filePath)) {
         //resize picture to label size
         QSize size(m_ui->lblPhoto->width(), m_ui->lblPhoto->height());
         //show photo in grayscale (monochrome photography)
         if (PreferenceProvider::instance().grayscale()) {
             const auto grey = m_photo.toImage().convertToFormat(QImage::Format_Grayscale8);
             m_photo.convertFromImage(grey);
         }
         //scale photo and show it immediately
         m_photo = m_photo.scaled(size, Qt::KeepAspectRatio, Qt::SmoothTransformation);
         m_ui->lblPhoto->setPixmap(m_photo);
         m_ui->lblPhoto->repaint();
     } else {
         m_ui->statusBar->showMessage(tr("Couldn't load the photo."), STATUSBAR_MSG_TIMEOUT);
     }
 }
References FotoBox::PreferenceProvider::instance().
mouseReleaseEvent()
void FotoBox::FotoBox::mouseReleaseEvent (QMouseEvent * event) override private
This event handler, for event event, can be reimplemented in a subclass to receive mouse release events for the widget.
no buttons on UI and left click
See also
emit start()
Parameters
event QMouseEvent
Definition at line 178 of file fotobox.cpp.
 {
     //touch support only when no buttons are shown
     if (!PreferenceProvider::instance().showButtons() && (event->button() == Qt::LeftButton || event->button() == Qt::RightButton)) {
         Q_EMIT start();
         return;
     }
     QWidget::mouseReleaseEvent(event);
 }
References FotoBox::PreferenceProvider::instance().
operator=() [1/2]
FotoBox& FotoBox::FotoBox::operator= (const FotoBox & other) delete
FotoBox default copy assignment.
operator=() [2/2]
FotoBox& FotoBox::FotoBox::operator= (FotoBox && other) delete
FotoBox default move assignment.
photo
void FotoBox::FotoBox::photo () private slot
trigger camera to shot a photo and try to show it
Definition at line 208 of file fotobox.cpp.
 {
     //show label and hide other widgets
     m_ui->lcdCountdown->hide();
     QCoreApplication::processEvents(QEventLoop::ExcludeUserInputEvents);
     //remove current photo
     m_ui->lblPhoto->show();
     m_ui->lblPhoto->clear();
     m_ui->lblPhoto->repaint();
     //take a photo
     if (m_camera.shootPhoto()) {
         //load photo
         loadPhoto(m_photoDir + m_camera.currentPhoto());
     } else {
         m_ui->statusBar->showMessage(tr("Error: Taking a photo isn't working correctly!"), STATUSBAR_MSG_TIMEOUT);
     }
     //restart countdown and Buzzer
     if (PreferenceProvider::instance().countdown() > 0) {
         m_countdown.reset();
     }
 #if defined(BUZZER_AVAILABLE)
     if (PreferenceProvider::instance().queryInterval() > 0) {
         emit startBuzzer();
     }
 #endif
 }
References FotoBox::PreferenceProvider::instance().
preferenceDialog
void FotoBox::FotoBox::preferenceDialog () private slot
show preference dialog and close dialog
Definition at line 189 of file fotobox.cpp.
 {
     //Preferences dialog
     auto *dialog = new Preferences;
     //restore mouse cursor
     QApplication::restoreOverrideCursor();
     //close fotobox and show preferences
     reject();
 #if defined(Q_OS_MACOS)
     //QTBUG-36714: Window can't be closed on Mac OS X after calling showFullScreen()
     closeFullscreenWindowOnMac();
 #endif
     dialog->show();
 }
start
void FotoBox::FotoBox::start () signal
signal: start FotoBox
startBuzzer
void FotoBox::FotoBox::startBuzzer () signal
signal: start query pin with Buzzer class
Member Data Documentation
COMPARE
constexpr double FotoBox::FotoBox::COMPARE = 1.25 static constexpr private
1.25
Definition at line 139 of file fotobox.h.
m_buzzer
Buzzer FotoBox::FotoBox::m_buzzer private
buzzer using pigpio library
Definition at line 151 of file fotobox.h.
m_camera
Camera FotoBox::FotoBox::m_camera private
Camera (shot photo)
Definition at line 154 of file fotobox.h.
m_countdown
Countdown FotoBox::FotoBox::m_countdown private
Countdown
Definition at line 145 of file fotobox.h.
m_photo
QPixmap FotoBox::FotoBox::m_photo private
store / load the photo
Definition at line 157 of file fotobox.h.
m_photoDir
const QString FotoBox::FotoBox::m_photoDir private
photo directory
Definition at line 160 of file fotobox.h.
m_preferenceKey
const std::vector<Qt::Key> FotoBox::FotoBox::m_preferenceKey {Qt::Key_P, Qt::Key_S, Qt::Key_E} private
keyboard shortcut to go back to preference dialog
Definition at line 167 of file fotobox.h.
m_quitKey
const std::vector<Qt::Key> FotoBox::FotoBox::m_quitKey {Qt::Key_Escape, Qt::Key_Q} private
keyboard shortcut to quit the application
Definition at line 170 of file fotobox.h.
m_triggerKey
const std::vector<Qt::Key> FotoBox::FotoBox::m_triggerKey {Qt::Key_N, Qt::Key_Return, Qt::Key_Enter, Qt::Key_PageDown, Qt::Key_PageUp, Qt::Key_Left, Qt::Key_Right, Qt::Key_Up, Qt::Key_Down, Qt::Key_Space, Qt::Key_Backspace} private
keyboard shortcut to start FotoBox
Definition at line 164 of file fotobox.h.
m_ui
Ui::FotoBoxDialog* FotoBox::FotoBox::m_ui private
User Interface
Definition at line 142 of file fotobox.h.
m_workerThread
QThread FotoBox::FotoBox::m_workerThread private
handle Buzzer thread (Raspberry Pi GPIO)
Definition at line 148 of file fotobox.h.
STATUSBAR_MSG_TIMEOUT
constexpr int FotoBox::FotoBox::STATUSBAR_MSG_TIMEOUT = 8000 static constexpr private
status bar timout value
Definition at line 136 of file fotobox.h.
The documentation for this class was generated from the following files:
fotobox.h
fotobox.cpp
fotoboxmac.mm