FotoBox: Camera Class Reference
Camera Class Reference
The Camera class Use gphoto2 to send commands to camera.
#include <camera.h>
Public Member Functions
Camera (QObject *parent=nullptr)
Camera constructor.
~Camera () override=default
Camera destructor.
Camera (const Camera &other)=delete
Camera default copy constructor.
Camera & operator= (const Camera &other)=delete
Camera default copy assignment.
Camera (Camera &&other)=delete
Camera default move constructor.
Camera & operator= (Camera &&other)=delete
Camera default move assignment.
auto shootPhoto () -> bool
shoot a photo with gphoto2
auto currentPhoto () const -> QString
return member
Private Attributes
const int m_timeoutValue
QString m_currentPhoto
const QString m_photoSuffix
const QString m_cameraMode
const QStringList m_argList
QProcess m_process
Static Private Attributes
static constexpr int TO_SECONDS = 1000
Detailed Description
The Camera class Use gphoto2 to send commands to camera.
Definition at line 18 of file camera.h.
Constructor & Destructor Documentation
Camera() [1/3]
Camera::Camera (QObject * parent = nullptr) explicit
Camera constructor.
Parameters
parent QObjec
Definition at line 14 of file camera.cpp.
     : QObject(parent)
     , m_timeoutValue(TO_SECONDS * PreferenceProvider::instance().timeoutValue())
     , m_photoSuffix(PreferenceProvider::instance().photoName())
     , m_cameraMode(PreferenceProvider::instance().cameraMode())
     , m_argList(PreferenceProvider::instance().argumentLine().split(QChar(' ')))
     , m_process(this)
 {
     //call this function to save memory, if you are not interested in the output of the process
     m_process.closeReadChannel(QProcess::StandardOutput);
     m_process.closeReadChannel(QProcess::StandardError);
     //use 'photo folder' as working dir
     m_process.setWorkingDirectory(PreferenceProvider::instance().photoFolder());
 }
References PreferenceProvider::instance(), and m_process.
~Camera()
Camera::~Camera () override default
Camera destructor.
Camera() [2/3]
Camera::Camera (const Camera & other) delete
Camera default copy constructor.
Camera() [3/3]
Camera::Camera (Camera && other) delete
Camera default move constructor.
Member Function Documentation
currentPhoto()
auto Camera::currentPhoto () const -> QString
return member
See also
m_currentPhoto
Returns
filepath current photo
Definition at line 46 of file camera.cpp.
 {
     return m_currentPhoto;
 }
References m_currentPhoto.
Referenced by FotoBox::photo().
operator=() [1/2]
Camera& Camera::operator= (Camera && other) delete
Camera default move assignment.
operator=() [2/2]
Camera& Camera::operator= (const Camera & other) delete
Camera default copy assignment.
shootPhoto()
auto Camera::shootPhoto () -> bool
shoot a photo with gphoto2
Returns
true: processed finished / false: error
Definition at line 30 of file camera.cpp.
 {
     //file name of photo
     m_currentPhoto = QDateTime::currentDateTime().toString(QStringLiteral("yyyyMMdd_HH-mm-ss_")) + m_photoSuffix;
     //add filename to argument
     auto arguments = m_argList;
     arguments = arguments.replaceInStrings(QStringLiteral("%1"), m_currentPhoto);
     //start programm with given arguments
     m_process.start(m_cameraMode, arguments, {});
     m_process.waitForFinished(m_timeoutValue);
     //check time out and process exit code
     return (m_process.exitCode() == EXIT_SUCCESS);
 }
Referenced by FotoBox::photo().
Member Data Documentation
m_argList
const QStringList Camera::m_argList private
list of command line arguments
Definition at line 83 of file camera.h.
m_cameraMode
const QString Camera::m_cameraMode private
camera mode
Definition at line 80 of file camera.h.
m_currentPhoto
QString Camera::m_currentPhoto private
name of the current photo
Definition at line 74 of file camera.h.
Referenced by currentPhoto().
m_photoSuffix
const QString Camera::m_photoSuffix private
name of the photo
Definition at line 77 of file camera.h.
m_process
QProcess Camera::m_process private
executing commands
Definition at line 86 of file camera.h.
Referenced by Camera().
m_timeoutValue
const int Camera::m_timeoutValue private
time out value
Definition at line 71 of file camera.h.
TO_SECONDS
constexpr int Camera::TO_SECONDS = 1000 static constexpr private
used to convert msec to sec
Definition at line 68 of file camera.h.
The documentation for this class was generated from the following files:
camera.h
camera.cpp