FotoBox: FotoBox::PreferenceProvider Class Reference
FotoBox::PreferenceProvider Class Reference
Preference who stores the preferences.
#include <preferenceprovider.h>
Public Slots
void setPhotoFolder (const QString &i_value)
set photo output directory
void setPhotoName (const QString &i_value)
set photo name template
void setCountdownColor (const QString &i_value)
set font color of the countdown
void setBackgroundColor (const QString &i_value)
set background color of the FotoBox UI
void setCameraMode (const QString &i_value)
set the camera framework to be used
void setArgumentLine (const QString &i_value)
set camera framework arguments
void setCountdown (int i_value)
set countdown until photo is taken
void setInputPin (unsigned int i_value)
set pigpio GPIO input pin
void setOutputPin (unsigned int i_value)
set pigpio GPIO output pin
void setQueryInterval (unsigned int i_value)
set how often the pin should be queried
void setTimeoutValue (int i_value)
set timeout value for the camera framework
void setGrayscale (bool i_value)
set grayscale bool (monochrome photography)
void setShowButtons (bool i_value)
set whether buttons are displayed on the UI
void setPrint (bool i_value)
set print on or off
void setPrinterName (const QString &i_value)
set printer name
Signals
void photoFolderChanged (QString)
signal: photo output directory has changed
void photoNameChanged (QString)
signal: photo name template has changed
void countdownColorChanged (QString)
signal: font color of the countdown has changed
void backgroundColorChanged (QString)
signal: background color of the FotoBox UI has changed
void cameraModeChanged (QString)
signal: the camera framework to be used has changed
void argumentLineChanged (QString)
signal: camera framework arguments has changed
void countdownChanged (int)
signal: countdown until photo is taken has changed
void inputPinChanged (unsigned int)
signal: pigpio GPIO input pin has changed
void outputPinChanged (unsigned int)
signal: pigpio GPIO output pin has changed
void queryIntervalChanged (unsigned int)
signal: how often the pin should be queried has changed
void timeoutValueChanged (int)
signal: timeout value for the camera framework has changed
void grayscaleChanged (bool)
signal: grayscale (monochrome photography) has changed
void showButtonsChanged (bool)
signal: whether buttons are displayed on the UI has changed
void printChanged (bool)
signal: print has changed
void printerNameChanged (QString)
signal: printer name has changed
Public Member Functions
PreferenceProvider (const PreferenceProvider &)=delete
PreferenceProvider delete copy constructor (Singleton)
PreferenceProvider & operator= (const PreferenceProvider &)=delete
PreferenceProvider delete copy assignment (Singleton)
PreferenceProvider (PreferenceProvider &&other)=delete
PreferenceProvider delete move constructor (Singleton)
PreferenceProvider & operator= (PreferenceProvider &&other)=delete
PreferenceProvider delete move assignment (Singleton)
auto photoFolder () const -> QString
photo output directory
auto photoName () const -> QString
photo name template
auto countdownColor () const -> QString
font color of the countdown
auto backgroundColor () const -> QString
background color of the FotoBox UI
QString cameraMode () const
the camera framework to be used
auto argumentLine () const -> QString
camera framework arguments
auto countdown () const -> int
countdown until photo is taken
auto inputPin () const -> unsigned int
pigpio GPIO input pin
auto outputPin () const -> unsigned int
pigpio GPIO output pin
auto queryInterval () const -> unsigned int
how often the pin should be queried
auto timeoutValue () const -> int
timeout value for the camera framework
auto grayscale () const -> bool
show photo in grayscale (monochrome photography)
auto showButtons () const -> bool
buttons are displayed on the UI
auto print () const -> bool
print on or off
auto printerName () const -> QString
printer name
Static Public Member Functions
static PreferenceProvider & instance ()
get instance (Meyers Singleton)
Properties
QString photoFolder
QString photoName
QString countdownColor
QString backgroundColor
QString cameraMode
QString argumentLine
int countdown
unsigned int inputPin
unsigned int outputPin
unsigned int queryInterval
int timeoutValue
bool grayscale
bool showButtons
bool print
QString printerName
Private Member Functions
PreferenceProvider (QObject *parent=nullptr)
hide Preferences default constructor (Singleton)
~PreferenceProvider () override=default
hide Preferences destructor (Singleton)
Private Attributes
QString m_photoFolder
QString m_photoName
QString m_countdownColor
QString m_backgroundColor
QString m_cameraMode
QString m_argumentLine
int m_countdown = 0
unsigned int m_inputPin = 0
unsigned int m_outputPin = 0
unsigned int m_queryInterval = 0
int m_timeoutValue = 0
bool m_grayscale = false
bool m_showButtons = false
bool m_print = false
QString m_printerName
Detailed Description
Preference who stores the preferences.
Definition at line 18 of file preferenceprovider.h.
Constructor & Destructor Documentation
PreferenceProvider() [1/3]
FotoBox::PreferenceProvider::PreferenceProvider (QObject * parent = nullptr) explicit private
hide Preferences default constructor (Singleton)
Parameters
parent QObject
Definition at line 19 of file preferenceprovider.cpp.
                                                  : QObject(nullptr)
 {
 }
~PreferenceProvider()
FotoBox::PreferenceProvider::~PreferenceProvider () override private default
hide Preferences destructor (Singleton)
PreferenceProvider() [2/3]
FotoBox::PreferenceProvider::PreferenceProvider (const PreferenceProvider &) delete
PreferenceProvider delete copy constructor (Singleton)
PreferenceProvider() [3/3]
FotoBox::PreferenceProvider::PreferenceProvider (PreferenceProvider && other) delete
PreferenceProvider delete move constructor (Singleton)
Member Function Documentation
argumentLine()
auto FotoBox::PreferenceProvider::argumentLine () const -> QString
camera framework arguments
Returns
QString
See also
m_argumentLine
Definition at line 115 of file preferenceprovider.cpp.
 {
     return m_argumentLine;
 }
References m_argumentLine.
argumentLineChanged
void FotoBox::PreferenceProvider::argumentLineChanged (QString) signal
signal: camera framework arguments has changed
Referenced by setArgumentLine().
backgroundColor()
auto FotoBox::PreferenceProvider::backgroundColor () const -> QString
background color of the FotoBox UI
Returns
QString
See also
m_backgroundColor
Definition at line 85 of file preferenceprovider.cpp.
 {
     return m_backgroundColor;
 }
References m_backgroundColor.
backgroundColorChanged
void FotoBox::PreferenceProvider::backgroundColorChanged (QString) signal
signal: background color of the FotoBox UI has changed
Referenced by setBackgroundColor().
cameraMode()
auto FotoBox::PreferenceProvider::cameraMode () const
the camera framework to be used
Returns
QString
See also
m_cameraMode
Definition at line 100 of file preferenceprovider.cpp.
 {
     return m_cameraMode;
 }
References m_cameraMode.
cameraModeChanged
void FotoBox::PreferenceProvider::cameraModeChanged (QString) signal
signal: the camera framework to be used has changed
Referenced by setCameraMode().
countdown()
auto FotoBox::PreferenceProvider::countdown () const -> int
countdown until photo is taken
Returns
int
See also
m_countdown
Definition at line 55 of file preferenceprovider.cpp.
 {
     return m_countdown;
 }
References m_countdown.
countdownChanged
void FotoBox::PreferenceProvider::countdownChanged (int) signal
signal: countdown until photo is taken has changed
Referenced by setCountdown().
countdownColor()
auto FotoBox::PreferenceProvider::countdownColor () const -> QString
font color of the countdown
Returns
QString
See also
m_countdownColor
Definition at line 70 of file preferenceprovider.cpp.
 {
     return m_countdownColor;
 }
References m_countdownColor.
countdownColorChanged
void FotoBox::PreferenceProvider::countdownColorChanged (QString) signal
signal: font color of the countdown has changed
Referenced by setCountdownColor().
grayscale()
auto FotoBox::PreferenceProvider::grayscale () const -> bool
show photo in grayscale (monochrome photography)
Returns
bool
See also
m_grayscale
Definition at line 190 of file preferenceprovider.cpp.
 {
     return m_grayscale;
 }
References m_grayscale.
grayscaleChanged
void FotoBox::PreferenceProvider::grayscaleChanged (bool) signal
signal: grayscale (monochrome photography) has changed
Referenced by setGrayscale().
inputPin()
auto FotoBox::PreferenceProvider::inputPin () const -> unsigned int
pigpio GPIO input pin
Returns
unsigned int
See also
m_inputPin
Definition at line 130 of file preferenceprovider.cpp.
 {
     return m_inputPin;
 }
References m_inputPin.
inputPinChanged
void FotoBox::PreferenceProvider::inputPinChanged (unsigned int) signal
signal: pigpio GPIO input pin has changed
Referenced by setInputPin().
instance()
auto FotoBox::PreferenceProvider::instance () static
get instance (Meyers Singleton)
Returns
Preferences&
Definition at line 12 of file preferenceprovider.cpp.
 {
     //thread safe static initializer
     static PreferenceProvider instance;
     return instance;
 }
Referenced by FotoBox::FotoBox::buttons(), FotoBox::Camera::Camera(), FotoBox::Preferences::connectUi(), FotoBox::FotoBox::countdown(), FotoBox::FotoBox::drawText(), FotoBox::FotoBox::FotoBox(), FotoBox::FotoBox::loadPhoto(), FotoBox::FotoBox::mouseReleaseEvent(), FotoBox::FotoBox::photo(), and FotoBox::FotoBox::~FotoBox().
operator=() [1/2]
PreferenceProvider& FotoBox::PreferenceProvider::operator= (const PreferenceProvider &) delete
PreferenceProvider delete copy assignment (Singleton)
operator=() [2/2]
PreferenceProvider& FotoBox::PreferenceProvider::operator= (PreferenceProvider && other) delete
PreferenceProvider delete move assignment (Singleton)
outputPin()
auto FotoBox::PreferenceProvider::outputPin () const -> unsigned int
pigpio GPIO output pin
Returns
unsigned int
See also
m_outputPin
Definition at line 145 of file preferenceprovider.cpp.
 {
     return m_outputPin;
 }
References m_outputPin.
outputPinChanged
void FotoBox::PreferenceProvider::outputPinChanged (unsigned int) signal
signal: pigpio GPIO output pin has changed
Referenced by setOutputPin().
photoFolder()
auto FotoBox::PreferenceProvider::photoFolder () const -> QString
photo output directory
Returns
QString
See also
m_photoFolder
Definition at line 25 of file preferenceprovider.cpp.
 {
     return m_photoFolder;
 }
References m_photoFolder.
photoFolderChanged
void FotoBox::PreferenceProvider::photoFolderChanged (QString) signal
signal: photo output directory has changed
Referenced by setPhotoFolder().
photoName()
auto FotoBox::PreferenceProvider::photoName () const -> QString
photo name template
Returns
QString
See also
m_photoName
Definition at line 40 of file preferenceprovider.cpp.
 {
     return m_photoName;
 }
References m_photoName.
photoNameChanged
void FotoBox::PreferenceProvider::photoNameChanged (QString) signal
signal: photo name template has changed
Referenced by setPhotoName().
print()
auto FotoBox::PreferenceProvider::print () const -> bool
print on or off
Returns
bool
See also
m_print
Definition at line 220 of file preferenceprovider.cpp.
 {
     return m_print;
 }
References m_print.
printChanged
void FotoBox::PreferenceProvider::printChanged (bool) signal
signal: print has changed
Referenced by setPrint().
printerName()
auto FotoBox::PreferenceProvider::printerName () const -> QString
printer name
Returns
QString
See also
m_printerName
Definition at line 235 of file preferenceprovider.cpp.
 {
     return m_printerName;
 }
References m_printerName.
printerNameChanged
void FotoBox::PreferenceProvider::printerNameChanged (QString) signal
signal: printer name has changed
Referenced by setPrinterName().
queryInterval()
auto FotoBox::PreferenceProvider::queryInterval () const -> unsigned int
how often the pin should be queried
Returns
unsigned int
See also
m_queryInterval
Definition at line 160 of file preferenceprovider.cpp.
 {
     return m_queryInterval;
 }
References m_queryInterval.
queryIntervalChanged
void FotoBox::PreferenceProvider::queryIntervalChanged (unsigned int) signal
signal: how often the pin should be queried has changed
Referenced by setQueryInterval().
setArgumentLine
void FotoBox::PreferenceProvider::setArgumentLine (const QString & i_value) slot
set camera framework arguments
Parameters
i_value QString&
Definition at line 120 of file preferenceprovider.cpp.
 {
     if (m_argumentLine == i_value) {
         return;
     }
     m_argumentLine = i_value;
     Q_EMIT argumentLineChanged(m_argumentLine);
 }
References argumentLineChanged(), and m_argumentLine.
Referenced by FotoBox::Preferences::connectUi().
setBackgroundColor
void FotoBox::PreferenceProvider::setBackgroundColor (const QString & i_value) slot
set background color of the FotoBox UI
Parameters
i_value QString&
Definition at line 90 of file preferenceprovider.cpp.
 {
     if (m_backgroundColor == i_value) {
         return;
     }
     m_backgroundColor = i_value;
     Q_EMIT backgroundColorChanged(m_backgroundColor);
 }
References backgroundColorChanged(), and m_backgroundColor.
Referenced by FotoBox::Preferences::connectUi().
setCameraMode
void FotoBox::PreferenceProvider::setCameraMode (const QString & i_value) slot
set the camera framework to be used
Parameters
i_value QString&
Definition at line 105 of file preferenceprovider.cpp.
 {
     if (m_cameraMode == i_value) {
         return;
     }
     m_cameraMode = i_value;
     Q_EMIT cameraModeChanged(m_cameraMode);
 }
References cameraModeChanged(), and m_cameraMode.
Referenced by FotoBox::Preferences::connectUi().
setCountdown
void FotoBox::PreferenceProvider::setCountdown (int i_value) slot
set countdown until photo is taken
Parameters
i_value int
Definition at line 60 of file preferenceprovider.cpp.
 {
     if (m_countdown == i_value) {
         return;
     }
     m_countdown = i_value;
     Q_EMIT countdownChanged(m_countdown);
 }
References countdownChanged(), and m_countdown.
Referenced by FotoBox::Preferences::connectUi().
setCountdownColor
void FotoBox::PreferenceProvider::setCountdownColor (const QString & i_value) slot
set font color of the countdown
Parameters
i_value QString&
Definition at line 75 of file preferenceprovider.cpp.
 {
     if (m_countdownColor == i_value) {
         return;
     }
     m_countdownColor = i_value;
     Q_EMIT countdownColorChanged(m_countdownColor);
 }
References countdownColorChanged(), and m_countdownColor.
Referenced by FotoBox::Preferences::connectUi().
setGrayscale
void FotoBox::PreferenceProvider::setGrayscale (bool i_value) slot
set grayscale bool (monochrome photography)
Parameters
i_value int
Definition at line 195 of file preferenceprovider.cpp.
 {
     if (m_grayscale == i_value) {
         return;
     }
     m_grayscale = i_value;
     Q_EMIT grayscaleChanged(m_grayscale);
 }
References grayscaleChanged(), and m_grayscale.
Referenced by FotoBox::Preferences::connectUi().
setInputPin
void FotoBox::PreferenceProvider::setInputPin (unsigned int i_value) slot
set pigpio GPIO input pin
Parameters
i_value unsigned int
Definition at line 135 of file preferenceprovider.cpp.
 {
     if (m_inputPin == i_value) {
         return;
     }
     m_inputPin = i_value;
     Q_EMIT inputPinChanged(m_inputPin);
 }
References inputPinChanged(), and m_inputPin.
Referenced by FotoBox::Preferences::connectUi().
setOutputPin
void FotoBox::PreferenceProvider::setOutputPin (unsigned int i_value) slot
set pigpio GPIO output pin
Parameters
i_value unsigned int
Definition at line 150 of file preferenceprovider.cpp.
 {
     if (m_outputPin == i_value) {
         return;
     }
     m_outputPin = i_value;
     Q_EMIT outputPinChanged(m_outputPin);
 }
References m_outputPin, and outputPinChanged().
Referenced by FotoBox::Preferences::connectUi().
setPhotoFolder
void FotoBox::PreferenceProvider::setPhotoFolder (const QString & i_value) slot
set photo output directory
Parameters
i_value QString&
Definition at line 30 of file preferenceprovider.cpp.
 {
     if (m_photoFolder == i_value) {
         return;
     }
     m_photoFolder = i_value;
     Q_EMIT photoFolderChanged(m_photoFolder);
 }
References m_photoFolder, and photoFolderChanged().
Referenced by FotoBox::Preferences::connectUi().
setPhotoName
void FotoBox::PreferenceProvider::setPhotoName (const QString & i_value) slot
set photo name template
Parameters
i_value QString&
Definition at line 45 of file preferenceprovider.cpp.
 {
     if (m_photoName == i_value) {
         return;
     }
     m_photoName = i_value;
     Q_EMIT photoNameChanged(m_photoName);
 }
References m_photoName, and photoNameChanged().
Referenced by FotoBox::Preferences::connectUi().
setPrint
void FotoBox::PreferenceProvider::setPrint (bool i_value) slot
set print on or off
Parameters
i_value bool
Definition at line 225 of file preferenceprovider.cpp.
 {
     if (m_print == i_value) {
         return;
     }
     m_print = i_value;
     Q_EMIT printChanged(m_print);
 }
References m_print, and printChanged().
Referenced by FotoBox::Preferences::connectUi().
setPrinterName
void FotoBox::PreferenceProvider::setPrinterName (const QString & i_value) slot
set printer name
Parameters
i_value QString&
Definition at line 240 of file preferenceprovider.cpp.
 {
     if (m_printerName == i_value) {
         return;
     }
     m_printerName = i_value;
     Q_EMIT printerNameChanged(m_printerName);
 }
References m_printerName, and printerNameChanged().
Referenced by FotoBox::Preferences::connectUi().
setQueryInterval
void FotoBox::PreferenceProvider::setQueryInterval (unsigned int i_value) slot
set how often the pin should be queried
Parameters
i_value unsigned int
Definition at line 165 of file preferenceprovider.cpp.
 {
     if (m_queryInterval == i_value) {
         return;
     }
     m_queryInterval = i_value;
     Q_EMIT queryIntervalChanged(m_queryInterval);
 }
References m_queryInterval, and queryIntervalChanged().
Referenced by FotoBox::Preferences::connectUi().
setShowButtons
void FotoBox::PreferenceProvider::setShowButtons (bool i_value) slot
set whether buttons are displayed on the UI
Parameters
i_value bool
Definition at line 210 of file preferenceprovider.cpp.
 {
     if (m_showButtons == i_value) {
         return;
     }
     m_showButtons = i_value;
     Q_EMIT showButtonsChanged(m_showButtons);
 }
References m_showButtons, and showButtonsChanged().
Referenced by FotoBox::Preferences::connectUi().
setTimeoutValue
void FotoBox::PreferenceProvider::setTimeoutValue (int i_value) slot
set timeout value for the camera framework
Parameters
i_value int
Definition at line 180 of file preferenceprovider.cpp.
 {
     if (m_timeoutValue == i_value) {
         return;
     }
     m_timeoutValue = i_value;
     Q_EMIT timeoutValueChanged(m_timeoutValue);
 }
References m_timeoutValue, and timeoutValueChanged().
Referenced by FotoBox::Preferences::connectUi().
showButtons()
auto FotoBox::PreferenceProvider::showButtons () const -> bool
buttons are displayed on the UI
Returns
bool
See also
m_showButtons
Definition at line 205 of file preferenceprovider.cpp.
 {
     return m_showButtons;
 }
References m_showButtons.
showButtonsChanged
void FotoBox::PreferenceProvider::showButtonsChanged (bool) signal
signal: whether buttons are displayed on the UI has changed
Referenced by setShowButtons().
timeoutValue()
auto FotoBox::PreferenceProvider::timeoutValue () const -> int
timeout value for the camera framework
Returns
int
See also
m_timeoutValue
Definition at line 175 of file preferenceprovider.cpp.
 {
     return m_timeoutValue;
 }
References m_timeoutValue.
timeoutValueChanged
void FotoBox::PreferenceProvider::timeoutValueChanged (int) signal
signal: timeout value for the camera framework has changed
Referenced by setTimeoutValue().
Member Data Documentation
m_argumentLine
QString FotoBox::PreferenceProvider::m_argumentLine private
camera framework arguments
Definition at line 50 of file preferenceprovider.h.
Referenced by argumentLine(), and setArgumentLine().
m_backgroundColor
QString FotoBox::PreferenceProvider::m_backgroundColor private
background color of the FotoBox UI
Definition at line 44 of file preferenceprovider.h.
Referenced by backgroundColor(), and setBackgroundColor().
m_cameraMode
QString FotoBox::PreferenceProvider::m_cameraMode private
the camera framework to be used
Definition at line 47 of file preferenceprovider.h.
Referenced by cameraMode(), and setCameraMode().
m_countdown
int FotoBox::PreferenceProvider::m_countdown = 0 private
countdown until photo is taken
Definition at line 53 of file preferenceprovider.h.
Referenced by countdown(), and setCountdown().
m_countdownColor
QString FotoBox::PreferenceProvider::m_countdownColor private
font color of the countdown
Definition at line 41 of file preferenceprovider.h.
Referenced by countdownColor(), and setCountdownColor().
m_grayscale
bool FotoBox::PreferenceProvider::m_grayscale = false private
show photo in grayscale (monochrome photography)
Definition at line 68 of file preferenceprovider.h.
Referenced by grayscale(), and setGrayscale().
m_inputPin
unsigned int FotoBox::PreferenceProvider::m_inputPin = 0 private
pigpio GPIO input pin
Definition at line 56 of file preferenceprovider.h.
Referenced by inputPin(), and setInputPin().
m_outputPin
unsigned int FotoBox::PreferenceProvider::m_outputPin = 0 private
pigpio GPIO output pin
Definition at line 59 of file preferenceprovider.h.
Referenced by outputPin(), and setOutputPin().
m_photoFolder
QString FotoBox::PreferenceProvider::m_photoFolder private
photo output directory
Definition at line 35 of file preferenceprovider.h.
Referenced by photoFolder(), and setPhotoFolder().
m_photoName
QString FotoBox::PreferenceProvider::m_photoName private
photo name template
Definition at line 38 of file preferenceprovider.h.
Referenced by photoName(), and setPhotoName().
m_print
bool FotoBox::PreferenceProvider::m_print = false private
turn print on or off
Definition at line 74 of file preferenceprovider.h.
Referenced by print(), and setPrint().
m_printerName
QString FotoBox::PreferenceProvider::m_printerName private
printer name
Definition at line 77 of file preferenceprovider.h.
Referenced by printerName(), and setPrinterName().
m_queryInterval
unsigned int FotoBox::PreferenceProvider::m_queryInterval = 0 private
how often the pin should be queried
Definition at line 62 of file preferenceprovider.h.
Referenced by queryInterval(), and setQueryInterval().
m_showButtons
bool FotoBox::PreferenceProvider::m_showButtons = false private
buttons are displayed on the UI
Definition at line 71 of file preferenceprovider.h.
Referenced by setShowButtons(), and showButtons().
m_timeoutValue
int FotoBox::PreferenceProvider::m_timeoutValue = 0 private
timeout value for the camera framework
Definition at line 65 of file preferenceprovider.h.
Referenced by setTimeoutValue(), and timeoutValue().
Property Documentation
argumentLine
QString FotoBox::PreferenceProvider::argumentLine read write
Definition at line 77 of file preferenceprovider.h.
backgroundColor
QString FotoBox::PreferenceProvider::backgroundColor read write
Definition at line 77 of file preferenceprovider.h.
cameraMode
QString FotoBox::PreferenceProvider::cameraMode read write
Definition at line 77 of file preferenceprovider.h.
countdown
int FotoBox::PreferenceProvider::countdown read write
Definition at line 77 of file preferenceprovider.h.
countdownColor
QString FotoBox::PreferenceProvider::countdownColor read write
Definition at line 77 of file preferenceprovider.h.
grayscale
bool FotoBox::PreferenceProvider::grayscale read write
Definition at line 77 of file preferenceprovider.h.
inputPin
unsigned int FotoBox::PreferenceProvider::inputPin read write
Definition at line 77 of file preferenceprovider.h.
outputPin
unsigned int FotoBox::PreferenceProvider::outputPin read write
Definition at line 77 of file preferenceprovider.h.
photoFolder
QString FotoBox::PreferenceProvider::photoFolder read write
Definition at line 77 of file preferenceprovider.h.
photoName
QString FotoBox::PreferenceProvider::photoName read write
Definition at line 77 of file preferenceprovider.h.
print
bool FotoBox::PreferenceProvider::print read write
Definition at line 77 of file preferenceprovider.h.
printerName
QString FotoBox::PreferenceProvider::printerName read write
Definition at line 77 of file preferenceprovider.h.
queryInterval
unsigned int FotoBox::PreferenceProvider::queryInterval read write
Definition at line 77 of file preferenceprovider.h.
showButtons
bool FotoBox::PreferenceProvider::showButtons read write
Definition at line 77 of file preferenceprovider.h.
timeoutValue
int FotoBox::PreferenceProvider::timeoutValue read write
Definition at line 77 of file preferenceprovider.h.
The documentation for this class was generated from the following files:
preferenceprovider.h
preferenceprovider.cpp