FotoBox: Buzzer Class Reference
Buzzer Class Reference
This class handles the buzzer.
#include <buzzer.h>
Public Slots
void queryPin ()
Query the Raspberry Pi pin.
Signals
void triggered ()
Buzzer was pressed.
Public Member Functions
Buzzer (QObject *parent=nullptr)
Buzzer constructor.
~Buzzer () override=default
Buzzer destructor.
Buzzer (const Buzzer &)=delete
Buzzer copy constructor.
Buzzer & operator= (const Buzzer &)=delete
Buzzer delete copy assignment.
Buzzer (Buzzer &&other)=delete
Buzzer default move constructor.
Buzzer & operator= (Buzzer &&other)=delete
Buzzer default move assignment.
void stop ()
Stop executing.
Private Attributes
std::atomic< bool > m_stop {false}
Detailed Description
This class handles the buzzer.
Definition at line 25 of file buzzer.h.
Constructor & Destructor Documentation
Buzzer() [1/3]
Buzzer::Buzzer (QObject * parent = nullptr) explicit
Buzzer constructor.
Parameters
parent QObject
Definition at line 44 of file buzzer.cpp.
 : QObject(nullptr) {/* stub */};
~Buzzer()
Buzzer::~Buzzer () override default
Buzzer destructor.
Buzzer() [2/3]
Buzzer::Buzzer (const Buzzer &) delete
Buzzer copy constructor.
Buzzer() [3/3]
Buzzer::Buzzer (Buzzer && other) delete
Buzzer default move constructor.
Member Function Documentation
operator=() [1/2]
Buzzer& Buzzer::operator= (Buzzer && other) delete
Buzzer default move assignment.
operator=() [2/2]
Buzzer& Buzzer::operator= (const Buzzer &) delete
Buzzer delete copy assignment.
queryPin
void Buzzer::queryPin () slot
Query the Raspberry Pi pin.
Definition at line 45 of file buzzer.cpp.
 {/* stub */};
Referenced by FotoBox::buzzer().
stop()
void Buzzer::stop ()
Stop executing.
See also
queryPin()
Definition at line 49 of file buzzer.cpp.
 {
     //set std::atomic to true
     m_stop = true;
 }
References m_stop.
Referenced by FotoBox::~FotoBox().
triggered
void Buzzer::triggered () signal
Buzzer was pressed.
Referenced by FotoBox::buzzer().
Member Data Documentation
m_stop
std::atomic<bool> Buzzer::m_stop {false} private
atomic bool to stop
See also
queryPin()
Definition at line 80 of file buzzer.h.
Referenced by stop().
The documentation for this class was generated from the following files:
buzzer.h
buzzer.cpp