FotoBox: FotoBox::Countdown Class Reference
FotoBox::Countdown Class Reference
The Countdown class.
#include <countdown.h>
Signals
void update (unsigned int)
Update countdown.
void elapsed ()
Countdown elapsed.
Public Member Functions
Countdown (QObject *parent=nullptr, unsigned int i_seconds=0)
Countdown constructor.
~Countdown () override=default
Countdown default destructor.
Countdown (const Countdown &other)=delete
Countdown default copy constructor.
Countdown & operator= (const Countdown &other)=delete
Countdown default copy assignment.
Countdown (Countdown &&other)=delete
Countdown default move constructor.
Countdown & operator= (Countdown &&other)=delete
Countdown default move assignment.
void setStartTime (unsigned int i_seconds)
Set the countdown start time.
auto isActive () const -> bool
Show countdown status.
auto start () -> bool
Start countdown.
auto stop () -> bool
Stop countdown and check.
auto reset () -> bool
Reset countdown (reset.
Private Member Functions
void updateTimeLeft ()
Start the timer until there is no time left, means.
Private Attributes
QTimer m_timer
unsigned int m_startTime
unsigned int m_timeLeft
bool m_isActive {false}
Static Private Attributes
static constexpr int ONE_SECOND = 1000
Detailed Description
The Countdown class.
Provides a countdown which operates on the base of seconds
Definition at line 20 of file countdown.h.
Constructor & Destructor Documentation
Countdown() [1/3]
FotoBox::Countdown::Countdown (QObject * parent = nullptr, unsigned int i_seconds = 0) explicit
Countdown constructor.
Parameters
parent QObject
i_seconds set the start time
See also
m_startTime
Definition at line 12 of file countdown.cpp.
     : QObject(parent)
     , m_timer(this)
     , m_startTime(i_seconds)
     , m_timeLeft(i_seconds)
 {
     //set update intervall to one second
     m_timer.setInterval(ONE_SECOND);
     //Every second it is checked if the countdown is elapsed
     connect(&m_timer, &QTimer::timeout, this, &Countdown::updateTimeLeft);
 }
References m_timer, ONE_SECOND, and updateTimeLeft().
~Countdown()
FotoBox::Countdown::~Countdown () override default
Countdown default destructor.
Countdown() [2/3]
FotoBox::Countdown::Countdown (const Countdown & other) delete
Countdown default copy constructor.
Countdown() [3/3]
FotoBox::Countdown::Countdown (Countdown && other) delete
Countdown default move constructor.
Member Function Documentation
elapsed
void FotoBox::Countdown::elapsed () signal
Countdown elapsed.
See also
m_timeLeft reached zero
Referenced by FotoBox::FotoBox::countdown(), FotoBox::Preferences::Preferences(), and updateTimeLeft().
isActive()
auto FotoBox::Countdown::isActive () const -> bool
Show countdown status.
Returns
bool getter
See also
m_isActive true: is active / false: not active
Definition at line 52 of file countdown.cpp.
 {
     return m_isActive;
 }
References m_isActive.
operator=() [1/2]
Countdown& FotoBox::Countdown::operator= (const Countdown & other) delete
Countdown default copy assignment.
operator=() [2/2]
Countdown& FotoBox::Countdown::operator= (Countdown && other) delete
Countdown default move assignment.
reset()
auto FotoBox::Countdown::reset () -> bool
Reset countdown (reset.
See also
m_timeLeft value with
m_startTime)
Will also
See also
stop() current countdown
Returns
bool true: is reseted / false: not reseted
Definition at line 88 of file countdown.cpp.
 {
     //stop countdown
     if (stop()) {
         //reset it
         m_timeLeft = m_startTime;
         return true;
     }
     return false;
 }
Referenced by setStartTime().
setStartTime()
void FotoBox::Countdown::setStartTime (unsigned int i_seconds)
Set the countdown start time.
Parameters
i_seconds setter
See also
m_startTime
Definition at line 46 of file countdown.cpp.
 {
     m_startTime = i_seconds;
     reset();
 }
References m_startTime, and reset().
start()
auto FotoBox::Countdown::start () -> bool
Start countdown.
only start if not running
See also
m_isActive and start value
m_startValue is set
Returns
bool true: running / false: not running
Definition at line 57 of file countdown.cpp.
 {
     //not running and start time set
     if (!m_isActive && m_startTime > 0) {
         //start countdown
         m_timer.start();
         //check if really running
         if (m_timer.isActive()) {
             //countdown active
             m_isActive = true;
             //inform whith current value
             Q_EMIT update(m_timeLeft);
             return true;
         }
     }
     return false;
 }
Referenced by FotoBox::FotoBox::countdown(), and FotoBox::Preferences::Preferences().
stop()
auto FotoBox::Countdown::stop () -> bool
Stop countdown and check.
See also
m_timer has really stopped
Returns
bool true: is stopped / false: not stopped
Definition at line 78 of file countdown.cpp.
 {
     //stop timer
     m_timer.stop();
     m_isActive = m_timer.isActive();
     //if isn't active it's stopped so negate bool
     return !m_isActive;
 }
Referenced by updateTimeLeft().
update
void FotoBox::Countdown::update (unsigned int) signal
Update countdown.
Referenced by FotoBox::FotoBox::countdown(), FotoBox::Preferences::Preferences(), and updateTimeLeft().
updateTimeLeft()
void FotoBox::Countdown::updateTimeLeft () private
Start the timer until there is no time left, means.
See also
m_timeLeft reaches zero
Attention: this function always deals with the already expired second.
Definition at line 25 of file countdown.cpp.
 {
     //this function always deals with the already expired second
     //check if countdown isn't elapsed
     if (m_timeLeft > 1) {
         //reduce counter before sending the signal
         --m_timeLeft;
         //send the signal that one second has passed
         Q_EMIT update(m_timeLeft);
         //Because it isn't a single shot time we don't need to start it again
         return;
     }
     //countdown finished/elapsed
     stop();
     m_timeLeft = 0;
     Q_EMIT elapsed();
 }
References elapsed(), m_timeLeft, stop(), and update().
Referenced by Countdown().
Member Data Documentation
m_isActive
bool FotoBox::Countdown::m_isActive {false} private
status of the countdown
Definition at line 118 of file countdown.h.
Referenced by isActive().
m_startTime
unsigned int FotoBox::Countdown::m_startTime private
countdown start time (seconds)
Definition at line 112 of file countdown.h.
Referenced by setStartTime().
m_timeLeft
unsigned int FotoBox::Countdown::m_timeLeft private
time left (seconds)
Definition at line 115 of file countdown.h.
Referenced by updateTimeLeft().
m_timer
QTimer FotoBox::Countdown::m_timer private
timer intervall (one second)
Definition at line 109 of file countdown.h.
Referenced by Countdown().
ONE_SECOND
constexpr int FotoBox::Countdown::ONE_SECOND = 1000 static constexpr private
one second = 1000 ms
Definition at line 121 of file countdown.h.
Referenced by Countdown().
The documentation for this class was generated from the following files:
countdown.h
countdown.cpp