FotoBox: Preferences Class Reference
Preferences Class Reference
Preference class to change and store the application settings.
#include <preferences.h>
Public Member Functions
Preferences (QWidget *parent=nullptr)
Preferences constructor.
~Preferences () override
Preferences destructor.
Preferences (const Preferences &other)=delete
Preferences default copy constructor.
Preferences & operator= (const Preferences &other)=delete
Preferences default copy assignment.
Preferences (Preferences &&other)=delete
Preferences default move constructor.
Preferences & operator= (Preferences &&other)=delete
Preferences default move assignment.
Private Slots
void startFotoBox ()
Start the FotoBox.
void colorDialog ()
Open a color picker to choose background color for FotoBox.
void commandLineOptionsDialog ()
Show help dialog for gphoto2/raspistill command line options.
void chooseDirectory ()
Open a QFileDialog to choose the photo directory.
void clearDirectoryContent ()
Clear directory content of the photo directory.
void restoreDefaultPreferences ()
Restore default preferences.
void showColor (const QString &i_colorName)
Show the given color in QLineEdit.
void verifyApplication (const QString &i_name)
Check camera application availability and provide help if needed.
bool verifyPath (const QString &i_path)
Check if the path is useable.
Private Member Functions
void windowPosition ()
Set the window position.
void stopCountdownMode ()
Stop countdown, stop mouse tracking and set normal window title name.
void connectUi ()
Signal & Slot connect.
void loadPreferences ()
Load application settings from INI file.
void setButtonIcons ()
Set icons for all QToolButtons.
void savePreferences ()
Save the preferences to QSettings.
void mouseMoveEvent (QMouseEvent *event) override
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
auto applicationAvailable (const QString &i_name, const QString &i_message) -> bool
Check if application is installed and available.
auto gphotoInfo (const QString &i_name) -> QString
Read gphoto2 / libgphoto2 version and camera model.
Private Attributes
Ui::PreferencesDialog * m_ui
QSettings m_settings
Countdown m_countdown
Static Private Attributes
static constexpr int COUNTDOWN_START_VALUE = 10
static constexpr int DEFAULT_COUNTDOWN_START_VALUE = 3
static constexpr int DEFAULT_INPUT_PIN = 5
static constexpr int DEFAULT_OUTPUT_PIN = 0
static constexpr int DEFAULT_QUERY_INTERVAL = 10
static constexpr int DEFAULT_TIMEOUT = 30
Detailed Description
Preference class to change and store the application settings.
Definition at line 23 of file preferences.h.
Constructor & Destructor Documentation
Preferences() [1/3]
Preferences::Preferences (QWidget * parent = nullptr) explicit
Preferences constructor.
Parameters
parent QWidget
Definition at line 24 of file preferences.cpp.
     : QDialog(parent, Qt::Window)
     , m_ui(new Ui::PreferencesDialog)
     , m_settings(QSettings::IniFormat, QSettings::UserScope, QCoreApplication::applicationName(), QCoreApplication::applicationName(), this)
     , m_countdown(this, COUNTDOWN_START_VALUE)
 {
     //setup UI
     m_ui->setupUi(this);
     //set icons for QToolButtons
     setButtonIcons();
     //set window position
     windowPosition();
     //delete everything on close
     setAttribute(Qt::WA_DeleteOnClose);
     //DON'T CHANGE ORDER!
     //Signal & Slot
     connectUi();
     //restore default values
     restoreDefaultPreferences();
     //load settings from ini file
     loadPreferences();
     //auto accept Dialog
     connect(&m_countdown, &Countdown::elapsed, this, [&]() {
         //start FotoBox
         startFotoBox();
     });
     m_countdown.start();
     //update window title
     connect(&m_countdown, &Countdown::update, this, [&](unsigned int i_timeLeft) {
         //: %1 FotoBox %2 application version %3 countdown (number)
         setWindowTitle(tr("launching %1 v%2 in %3 seconds").arg(QApplication::applicationName(), QApplication::applicationVersion()).arg(i_timeLeft));
     });
 }
References connectUi(), Countdown::elapsed(), loadPreferences(), m_countdown, m_ui, restoreDefaultPreferences(), setButtonIcons(), Countdown::start(), startFotoBox(), Countdown::update(), and windowPosition().
~Preferences()
Preferences::~Preferences () override
Preferences destructor.
Definition at line 64 of file preferences.cpp.
 {
     delete m_ui;
 }
References m_ui.
Preferences() [2/3]
Preferences::Preferences (const Preferences & other) delete
Preferences default copy constructor.
Preferences() [3/3]
Preferences::Preferences (Preferences && other) delete
Preferences default move constructor.
Member Function Documentation
applicationAvailable()
auto Preferences::applicationAvailable (const QString & i_name, const QString & i_message) -> bool private
Check if application is installed and available.
Parameters
i_name QString name of the application to check
i_message QString error message to display in QLabel
Returns
bool true: application found / false: not found
Definition at line 467 of file preferences.cpp.
 {
     //If the process cannot be started, -2 is returned. If the process crashes, -1 is returned.
     QProcess process;
     process.start(i_name, {}, QIODevice::NotOpen);
     process.waitForFinished();
     const auto EXIT_CODE_OUT_OF_RANGE = 255;
     if (process.exitCode() == EXIT_CODE_OUT_OF_RANGE) {
         //set error message
         m_ui->lblCameraModeInfo->setStyleSheet(QStringLiteral("QLabel { color : red; }"));
         m_ui->lblCameraModeInfo->setText(i_message);
         m_ui->cmbCameraMode->setItemData(m_ui->cmbCameraMode->currentIndex(), QBrush(Qt::red), Qt::ForegroundRole);
         return false;
     }
     //application is available reset style and content
     m_ui->lblCameraModeInfo->setStyleSheet(QLatin1String(""));
     m_ui->lblCameraModeInfo->clear();
     m_ui->cmbCameraMode->setItemData(m_ui->cmbCameraMode->currentIndex(), QBrush(Qt::black), Qt::ForegroundRole);
     return true;
 }
Referenced by verifyApplication().
chooseDirectory
void Preferences::chooseDirectory () private slot
Open a QFileDialog to choose the photo directory.
Definition at line 272 of file preferences.cpp.
 {
     //File Dialog to choose photo folder
     QFileDialog dialog(this, tr("choose directory"), m_ui->txtPhotoFolder->text());
     dialog.setFileMode(QFileDialog::Directory);
     dialog.setOptions(QFileDialog::ShowDirsOnly | QFileDialog::DontResolveSymlinks);
     //only set it if user don't abort dialog
     if (dialog.exec() == QDialog::Accepted) {
         const auto path = dialog.directory().absolutePath();
         if (!verifyPath(path)) {
             return;
         }
         //set path will again call verifyPath() see Signal&Slot connection
         m_ui->txtPhotoFolder->setText(QDir::toNativeSeparators(path));
     }
 }
References m_ui, and verifyPath().
Referenced by connectUi().
clearDirectoryContent
void Preferences::clearDirectoryContent () private slot
Clear directory content of the photo directory.
Definition at line 290 of file preferences.cpp.
 {
     //get photo folder from preferences
     const QString photoFolder(PreferenceProvider::instance().PreferenceProvider::photoFolder());
     //ask user
     const auto &text = tr("Clear all JPEGs in the photo folder (leave subfolders untouched)?") + QStringLiteral("\n\"") + photoFolder + '\"';
     const auto &result = QMessageBox::warning(this, tr("WARNING: clear directory content"), text, QMessageBox::Yes | QMessageBox::No);
     if (result == QMessageBox::Yes) {
         //photo folder
         QDir dir(photoFolder);
         //JPEG file extension https://en.wikipedia.org/wiki/JPEG
         dir.setNameFilters({ QStringLiteral("*.jpg"), QStringLiteral("*.jpeg"), QStringLiteral("*.jpe"), QStringLiteral("*.jif"), QStringLiteral("*.jfif"), QStringLiteral("*.jfi") });
         const auto &entryList = dir.entryList(QDir::NoDotAndDotDot | QDir::Files);
         for(const auto &dirItem : entryList)
         {
             //remove all files
             dir.remove(dirItem);
         }
     }
 }
References PreferenceProvider::instance(), and PreferenceProvider::photoFolder.
Referenced by connectUi().
colorDialog
void Preferences::colorDialog () private slot
Open a color picker to choose background color for FotoBox.
Definition at line 240 of file preferences.cpp.
 {
     //"Color Picker" Dialog
     QColorDialog dialog(this);
     if (dialog.exec() == QDialog::Accepted) {
         //show the color which the user has selected
         const auto *button = qobject_cast<QToolButton *>(sender());
         if (button == m_ui->btnChooseColorCD) {
             //font countdown
             m_ui->txtShowColorCD->setText(dialog.selectedColor().name());
         }
         if (button == m_ui->btnChooseColorBG) {
             //background color
             m_ui->txtShowColorBG->setText(dialog.selectedColor().name());
         }
     }
 }
References m_ui.
Referenced by connectUi().
commandLineOptionsDialog
void Preferences::commandLineOptionsDialog () private slot
Show help dialog for gphoto2/raspistill command line options.
official documentation and usefull examples
Definition at line 259 of file preferences.cpp.
 {
     //'Qt::Tool' act like a window 'Qt::ToolTip' always on top
     auto *dialog = new QDialog(this, Qt::SplashScreen);
     Ui::CommandLineOptionsDialog ui;
     //setup UI
     ui.setupUi(dialog);
     //blocking until the user closes it
     dialog->exec();
 }
Referenced by connectUi().
connectUi()
void Preferences::connectUi () private
Signal & Slot connect.
Definition at line 81 of file preferences.cpp.
 {
     //stop countdown if the application isn't visible and selected to be in front.
     connect(qobject_cast<QApplication*>(QCoreApplication::instance()), &QGuiApplication::applicationStateChanged, this, [&](const Qt::ApplicationState state) {
         if (state != Qt::ApplicationActive) {
             stopCountdownMode();
         }
     });
     //connect UI to preferences
     connect(m_ui->txtPhotoFolder, &QLineEdit::textChanged, &PreferenceProvider::instance(), &PreferenceProvider::setPhotoFolder);
     connect(m_ui->txtPhotoFolder, &QLineEdit::textChanged, this, &Preferences::verifyPath);
     connect(m_ui->btnChooseDirectory, &QPushButton::clicked, this, &Preferences::chooseDirectory);
     connect(m_ui->btnClearDirectoryContent, &QPushButton::clicked, this, &Preferences::clearDirectoryContent);
     connect(m_ui->txtPhotoName, &QLineEdit::textChanged, &PreferenceProvider::instance(), &PreferenceProvider::setPhotoName);
     connect(m_ui->spbCountdown, static_cast<void (QSpinBox::*)(int)>(&QSpinBox::valueChanged), &PreferenceProvider::instance(), &PreferenceProvider::setCountdown);
     connect(m_ui->btnChooseColorCD, &QPushButton::clicked, this, &Preferences::colorDialog);
     connect(m_ui->txtShowColorCD, &QLineEdit::textChanged, &PreferenceProvider::instance(), &PreferenceProvider::setCountdownColor);
     connect(m_ui->txtShowColorCD, &QLineEdit::textChanged, m_ui->txtShowColorCD, &QLineEdit::setToolTip);
     connect(m_ui->txtShowColorCD, &QLineEdit::textChanged, this, &Preferences::showColor);
     connect(m_ui->chbButtons, &QAbstractButton::toggled, &PreferenceProvider::instance(), &PreferenceProvider::setShowButtons);
     connect(m_ui->btnChooseColorBG, &QPushButton::clicked, this, &Preferences::colorDialog);
     connect(m_ui->txtShowColorBG, &QLineEdit::textChanged, &PreferenceProvider::instance(), &PreferenceProvider::setBackgroundColor);
     connect(m_ui->txtShowColorBG, &QLineEdit::textChanged, m_ui->txtShowColorBG, &QLineEdit::setToolTip);
     connect(m_ui->txtShowColorBG, &QLineEdit::textChanged, this, &Preferences::showColor);
     connect(m_ui->spbInputPin, static_cast<void (QSpinBox::*)(int)>(&QSpinBox::valueChanged), &PreferenceProvider::instance(), &PreferenceProvider::setInputPin);
     connect(m_ui->spbOutputPin, static_cast<void (QSpinBox::*)(int)>(&QSpinBox::valueChanged), &PreferenceProvider::instance(), &PreferenceProvider::setOutputPin);
     connect(m_ui->spbQueryInterval, static_cast<void (QSpinBox::*)(int)>(&QSpinBox::valueChanged), &PreferenceProvider::instance(), &PreferenceProvider::setQueryInterval);
     connect(m_ui->cmbCameraMode, &QComboBox::currentTextChanged, &PreferenceProvider::instance(), &PreferenceProvider::setCameraMode);
     connect(m_ui->cmbCameraMode, static_cast<void (QComboBox::*)(int)>(&QComboBox::currentIndexChanged), this, [&]() {
         //QComboBox has changed, show stored data to QLineEdit
         m_ui->txtArgumentLine->setText(m_ui->cmbCameraMode->currentData().toString());
     });
     connect(m_ui->cmbCameraMode, &QComboBox::currentTextChanged, this, &Preferences::verifyApplication);
     connect(m_ui->btnCameraModeReload, &QAbstractButton::clicked, this, [&]() {
         verifyApplication(m_ui->cmbCameraMode->currentText());
     });
     connect(m_ui->txtArgumentLine, &QLineEdit::textChanged, &PreferenceProvider::instance(), &PreferenceProvider::setArgumentLine);
     connect(m_ui->txtArgumentLine, &QLineEdit::textChanged, this, [&](const QString &i_value) {
         //save changed text in QComboBox model
         m_ui->cmbCameraMode->setItemData(m_ui->cmbCameraMode->currentIndex(), i_value);
     });
     connect(m_ui->btnArgumentLineHelp, &QAbstractButton::clicked, this, &Preferences::commandLineOptionsDialog);
     connect(m_ui->spbTimout, static_cast<void (QSpinBox::*)(int)>(&QSpinBox::valueChanged), &PreferenceProvider::instance(), &PreferenceProvider::setTimeoutValue);
     connect(m_ui->chbGrayscale, &QAbstractButton::toggled, &PreferenceProvider::instance(), &PreferenceProvider::setGrayscale);
     connect(m_ui->chbPrint, &QAbstractButton::toggled, &PreferenceProvider::instance(), &PreferenceProvider::setPrint);
     connect(m_ui->cmbPrinterName, &QComboBox::currentTextChanged, &PreferenceProvider::instance(), &PreferenceProvider::setPrinterName);
     //connect buttons
     connect(m_ui->buttonBox, &QDialogButtonBox::accepted, this, &Preferences::startFotoBox);
     connect(m_ui->buttonBox, &QDialogButtonBox::rejected, this, &QDialog::reject);
     connect(m_ui->buttonBox, &QDialogButtonBox::clicked, this, [&](QAbstractButton *button) {
         //identify restore button, restore defaults and save it
         if (button == m_ui->buttonBox->button(QDialogButtonBox::RestoreDefaults)) {
             restoreDefaultPreferences();
             m_settings.sync();
         }
     });
     connect(m_ui->buttonBox, &QDialogButtonBox::helpRequested, this, [&]() {
         //request OS to open the URL
         QDesktopServices::openUrl( { QStringLiteral("https://gitlab.com/tomikais/fotobox/blob/master/README.md") } );
     });
 }
References chooseDirectory(), clearDirectoryContent(), colorDialog(), commandLineOptionsDialog(), PreferenceProvider::instance(), m_ui, PreferenceProvider::setArgumentLine(), PreferenceProvider::setBackgroundColor(), PreferenceProvider::setCameraMode(), PreferenceProvider::setCountdown(), PreferenceProvider::setCountdownColor(), PreferenceProvider::setGrayscale(), PreferenceProvider::setInputPin(), PreferenceProvider::setOutputPin(), PreferenceProvider::setPhotoFolder(), PreferenceProvider::setPhotoName(), PreferenceProvider::setPrint(), PreferenceProvider::setPrinterName(), PreferenceProvider::setQueryInterval(), PreferenceProvider::setShowButtons(), PreferenceProvider::setTimeoutValue(), showColor(), startFotoBox(), stopCountdownMode(), verifyApplication(), and verifyPath().
Referenced by Preferences().
gphotoInfo()
auto Preferences::gphotoInfo (const QString & i_name) -> QString private
Read gphoto2 / libgphoto2 version and camera model.
Parameters
i_name QString name of the application to check
Returns
QString return information
Definition at line 488 of file preferences.cpp.
 {
     QString result;
     //call 'gphoto2 --version --summary' and get output in english
     QProcess process(this);
     auto env = QProcessEnvironment::systemEnvironment();
     env.insert(QStringLiteral("LC_ALL"), QStringLiteral("C"));
     process.setProcessEnvironment(env);
     process.start(i_name, {QStringLiteral("--version"), QStringLiteral("--summary")});
     process.waitForFinished();
     const auto output = QString::fromLatin1(process.readAllStandardOutput());
     //^gphoto2\s{2,}(?<gphoto2>\d+\.\d+\.\d+).*\n^libgphoto2\s{2,}(?<libgphoto2>\d+\.\d+\.\d+)
     QString pattern(QStringLiteral("^gphoto2\\s{2,}(?<gphoto2>\\d+\\.\\d+\\.\\d+).*\\n^libgphoto2\\s{2,}(?<libgphoto2>\\d+\\.\\d+\\.\\d+)"));
     //use regex to get version string
     QRegularExpression regex(pattern, QRegularExpression::MultilineOption);
     auto match = regex.match(output);
     QString gphoto2(i_name);
     QString libgphoto2(QStringLiteral("libgphoto2"));
     if (match.hasMatch()) {
         gphoto2 += QStringLiteral(" v") + match.captured(gphoto2);
         libgphoto2 += QStringLiteral(" v") + match.captured(libgphoto2);
         result = gphoto2 + QStringLiteral(" / ") + libgphoto2;
         //^[Mm]odel:\s(.*$)
         pattern = QStringLiteral("^[Mm]odel:\\s(.*$)");
         //get camera model
         regex.setPattern(pattern);
         match = regex.match(output);
         result += QStringLiteral("\n");
         if (match.hasMatch()) {
             const auto matches = match.lastCapturedIndex();
             result += tr("camera model: %1").arg(match.captured(1));
             //more then one camera detected ('0' full match, '1' first match, '2' second match,...)
             if (matches > 2) {
                 for (int i = 2; i <= matches; ++i) {
                     result += QStringLiteral(" / ") + match.captured(i);
                 }
             }
         } else {
             result += tr("camera model: %1").arg(tr("NOT DETECTED"));
         }
     }
     return result;
 }
Referenced by verifyApplication().
loadPreferences()
void Preferences::loadPreferences () private
Load application settings from INI file.
Definition at line 196 of file preferences.cpp.
 {
     m_settings.beginGroup(QStringLiteral("FotoBox"));
     m_ui->txtPhotoFolder->setText(m_settings.value(m_ui->txtPhotoFolder->objectName(), m_ui->txtPhotoFolder->text()).toString());
     m_ui->txtPhotoName->setText(m_settings.value(m_ui->txtPhotoName->objectName(), m_ui->txtPhotoName->text()).toString());
     m_ui->spbCountdown->setValue(m_settings.value(m_ui->spbCountdown->objectName(), m_ui->spbCountdown->value()).toInt());
     m_ui->txtShowColorCD->setText(m_settings.value(m_ui->txtShowColorCD->objectName(), m_ui->txtShowColorCD->text()).toString());
     m_ui->chbButtons->setChecked(m_settings.value(m_ui->chbButtons->objectName(), m_ui->chbButtons->isChecked()).toBool());
     m_ui->txtShowColorBG->setText(m_settings.value(m_ui->txtShowColorBG->objectName(), m_ui->txtShowColorBG->text()).toString());
     m_settings.endGroup();
     m_settings.beginGroup(QStringLiteral("Buzzer"));
     m_ui->spbInputPin->setValue(m_settings.value(m_ui->spbInputPin->objectName(), m_ui->spbInputPin->value()).toInt());
     m_ui->spbOutputPin->setValue(m_settings.value(m_ui->spbOutputPin->objectName(), m_ui->spbOutputPin->value()).toInt());
     m_ui->spbQueryInterval->setValue(m_settings.value(m_ui->spbQueryInterval->objectName(), m_ui->spbQueryInterval->value()).toInt());
     m_settings.endGroup();
     m_settings.beginGroup(QStringLiteral("Camera"));
     //restore QComboBox model
     const auto data = m_settings.value(m_ui->cmbCameraMode->objectName() + QStringLiteral("Data")).toStringList();
     const auto text = m_settings.value(m_ui->cmbCameraMode->objectName() + QStringLiteral("Text")).toStringList();
     if (!data.empty()) {
         m_ui->cmbCameraMode->clear();
         for (int i = 0; i < data.count(); ++i) {
             m_ui->cmbCameraMode->addItem(text.at(i), data.at(i));
         }
     }
     m_ui->cmbCameraMode->setCurrentText(m_settings.value(m_ui->cmbCameraMode->objectName(), m_ui->cmbCameraMode->currentText()).toString());
     m_ui->spbTimout->setValue(m_settings.value(m_ui->spbTimout->objectName(), m_ui->spbTimout->value()).toInt());
     m_ui->chbGrayscale->setChecked(m_settings.value(m_ui->chbGrayscale->objectName(), m_ui->chbGrayscale->isChecked()).toBool());
     m_settings.endGroup();
     m_settings.beginGroup(QStringLiteral("PrintSetup"));
     m_ui->chbPrint->setChecked(m_settings.value(m_ui->chbPrint->objectName(), m_ui->chbPrint->isChecked()).toBool());
     const auto &printerName = m_settings.value(m_ui->cmbPrinterName->objectName(), m_ui->cmbPrinterName->currentText()).toString();
     const auto printer = m_ui->cmbPrinterName->findText(printerName);
     if (printer >= 0) {
         //printer still available so set it
         m_ui->cmbPrinterName->setCurrentIndex(printer);
     }
     m_settings.endGroup();
 }
References m_settings, and m_ui.
Referenced by Preferences().
mouseMoveEvent()
void Preferences::mouseMoveEvent (QMouseEvent * event) override private
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
stopping auto accept dialog
See also
autoAcceptDialog()
Definition at line 168 of file preferences.cpp.
 {
     stopCountdownMode();
     //call base class method
     QWidget::mouseMoveEvent(event);
 }
References stopCountdownMode().
operator=() [1/2]
Preferences& Preferences::operator= (const Preferences & other) delete
Preferences default copy assignment.
operator=() [2/2]
Preferences& Preferences::operator= (Preferences && other) delete
Preferences default move assignment.
restoreDefaultPreferences
void Preferences::restoreDefaultPreferences () private slot
Restore default preferences.
Definition at line 403 of file preferences.cpp.
 {
     //FotoBox
     m_ui->txtPhotoFolder->setText(QDir::toNativeSeparators(QStandardPaths::writableLocation(QStandardPaths::PicturesLocation)) + QDir::separator() + QApplication::applicationName());
     m_ui->txtPhotoName->setText(QStringLiteral("eventname.jpg"));
     m_ui->spbCountdown->setValue(DEFAULT_COUNTDOWN_START_VALUE);
     m_ui->txtShowColorCD->setText(QStringLiteral("#ff0000"));
     m_ui->chbButtons->setChecked(true);
     m_ui->txtShowColorBG->setText(QStringLiteral("#000000"));
     //Buzzer
     m_ui->spbInputPin->setValue(DEFAULT_INPUT_PIN);
     m_ui->spbOutputPin->setValue(DEFAULT_OUTPUT_PIN);
     m_ui->spbQueryInterval->setValue(DEFAULT_QUERY_INTERVAL);
     //Camera
     m_ui->cmbCameraMode->clear();
     m_ui->cmbCameraMode->addItem(QStringLiteral("gphoto2"), "--capture-image-and-download --keep --force-overwrite --filename %1");
     m_ui->cmbCameraMode->addItem(QStringLiteral("raspistill"), "--output %1 --width 1920 --height 1080 --quality 75 --nopreview --timeout 1");
     m_ui->spbTimout->setValue(DEFAULT_TIMEOUT);
     m_ui->chbGrayscale->setChecked(false);
     //Print Setup
     //get all printers and preselect default printer
     m_ui->cmbPrinterName->clear();
     m_ui->cmbPrinterName->addItems(QPrinterInfo::availablePrinterNames());
     auto defaultPrinter = m_ui->cmbPrinterName->findText(QPrinterInfo::defaultPrinterName());
     m_ui->cmbPrinterName->setCurrentIndex(defaultPrinter);
     m_ui->chbPrint->setChecked(true);
 }
References DEFAULT_COUNTDOWN_START_VALUE, DEFAULT_INPUT_PIN, DEFAULT_OUTPUT_PIN, DEFAULT_QUERY_INTERVAL, DEFAULT_TIMEOUT, and m_ui.
Referenced by Preferences().
savePreferences()
void Preferences::savePreferences () private
Save the preferences to QSettings.
Definition at line 361 of file preferences.cpp.
 {
     m_settings.beginGroup(QStringLiteral("FotoBox"));
     m_settings.setValue(m_ui->txtPhotoFolder->objectName(), PreferenceProvider::instance().photoFolder());
     m_settings.setValue(m_ui->txtPhotoName->objectName(), PreferenceProvider::instance().photoName());
     m_settings.setValue(m_ui->spbCountdown->objectName(), PreferenceProvider::instance().countdown());
     m_settings.setValue(m_ui->txtShowColorCD->objectName(), PreferenceProvider::instance().countdownColor());
     m_settings.setValue(m_ui->chbButtons->objectName(), PreferenceProvider::instance().showButtons());
     m_settings.setValue(m_ui->txtShowColorBG->objectName(), PreferenceProvider::instance().backgroundColor());
     m_settings.endGroup();
     m_settings.beginGroup(QStringLiteral("Buzzer"));
     m_settings.setValue(m_ui->spbInputPin->objectName(), PreferenceProvider::instance().inputPin());
     m_settings.setValue(m_ui->spbOutputPin->objectName(), PreferenceProvider::instance().outputPin());
     m_settings.setValue(m_ui->spbQueryInterval->objectName(), PreferenceProvider::instance().queryInterval());
     m_settings.endGroup();
     m_settings.beginGroup(QStringLiteral("Camera"));
     //save QComboBox model
     QStringList itemText;
     QStringList itemData;
     const auto size = m_ui->cmbCameraMode->count();
     itemText.reserve(size);
     itemData.reserve(size);
     for (int i = 0; i < size; ++i) {
         itemText << m_ui->cmbCameraMode->itemText(i);
         itemData << m_ui->cmbCameraMode->itemData(i).toString();
     }
     m_settings.setValue(m_ui->cmbCameraMode->objectName() + QStringLiteral("Text"), itemText);
     m_settings.setValue(m_ui->cmbCameraMode->objectName() + QStringLiteral("Data"), itemData);
     m_settings.setValue(m_ui->cmbCameraMode->objectName(), PreferenceProvider::instance().cameraMode());
     m_settings.setValue(m_ui->spbTimout->objectName(), PreferenceProvider::instance().timeoutValue());
     m_settings.setValue(m_ui->chbGrayscale->objectName(), PreferenceProvider::instance().grayscale());
     m_settings.endGroup();
     m_settings.beginGroup(QStringLiteral("PrintSetup"));
     m_settings.setValue(m_ui->chbPrint->objectName(), PreferenceProvider::instance().print());
     m_settings.setValue(m_ui->cmbPrinterName->objectName(), PreferenceProvider::instance().printerName());
     m_settings.endGroup();
 }
References PreferenceProvider::backgroundColor, PreferenceProvider::cameraMode, PreferenceProvider::countdown, PreferenceProvider::countdownColor, PreferenceProvider::grayscale, PreferenceProvider::inputPin, PreferenceProvider::instance(), m_settings, m_ui, PreferenceProvider::outputPin, PreferenceProvider::photoFolder, PreferenceProvider::photoName, PreferenceProvider::print, PreferenceProvider::printerName, PreferenceProvider::queryInterval, PreferenceProvider::showButtons, and PreferenceProvider::timeoutValue.
Referenced by startFotoBox().
setButtonIcons()
void Preferences::setButtonIcons () private
Set icons for all QToolButtons.
Definition at line 145 of file preferences.cpp.
 {
     //picture of all Qt standard icons: https://joekuan.files.wordpress.com/2015/09/screen3.png
     m_ui->btnChooseDirectory->setIcon(style()->standardIcon(QStyle::SP_DirOpenIcon));
     m_ui->btnClearDirectoryContent->setIcon(style()->standardIcon(QStyle::SP_DialogDiscardButton));
     m_ui->btnCameraModeReload->setIcon(style()->standardIcon(QStyle::SP_BrowserReload));
     m_ui->btnArgumentLineHelp->setIcon(style()->standardIcon(QStyle::SP_TitleBarContextHelpButton));
 }
References m_ui.
Referenced by Preferences().
showColor
void Preferences::showColor (const QString & i_colorName) private slot
Show the given color in QLineEdit.
Parameters
i_colorName QString hex name of the color
Definition at line 344 of file preferences.cpp.
 {
     //create color
     QColor color(i_colorName);
     //set color (text + background)
     auto *lineEdit = qobject_cast<QLineEdit *>(sender());
     if (lineEdit != nullptr) {
         auto palette = lineEdit->palette();
         palette.setColor(QPalette::Text, color);
         palette.setColor(QPalette::Base, color);
         lineEdit->setPalette(palette);
         //force repaint (Restore Default issue)
         lineEdit->repaint();
     }
 }
Referenced by connectUi().
startFotoBox
void Preferences::startFotoBox () private slot
Start the FotoBox.
Definition at line 154 of file preferences.cpp.
 {
     //save settings to ini file
     m_countdown.stop();
     savePreferences();
     //Start FotoBox;
     auto *dialog = new FotoBox;
     //close dialog and start fotobox
     reject();
     dialog->showFullScreen();
 }
References m_countdown, savePreferences(), and Countdown::stop().
Referenced by connectUi(), and Preferences().
stopCountdownMode()
void Preferences::stopCountdownMode () private
Stop countdown, stop mouse tracking and set normal window title name.
Definition at line 176 of file preferences.cpp.
 {
     if (m_countdown.isActive()) {
         //stop countdown
         m_countdown.stop();
         //disable mouse tracking (not needed anymore)
         setMouseTracking(false);
         m_ui->scrollArea->setMouseTracking(false);
         m_ui->scrollAreaWidgetContents->setMouseTracking(false);
         m_ui->tabWidget->setMouseTracking(false);
         m_ui->tabGeneral->setMouseTracking(false);
         m_ui->tabExpert->setMouseTracking(false);
         m_ui->buttonBox->setMouseTracking(false);
         //set normal window title
         setWindowTitle(QStringLiteral("%1 v%2 (Copyright 2016 %3) - ").arg(QApplication::applicationName(), QApplication::applicationVersion(), QApplication::organizationName()) + tr("preferences"));
     }
 }
References Countdown::isActive(), m_countdown, m_ui, and Countdown::stop().
Referenced by connectUi(), and mouseMoveEvent().
verifyApplication
void Preferences::verifyApplication (const QString & i_name) private slot
Check camera application availability and provide help if needed.
gphoto2: set version and camera model
Parameters
i_name QString name of the application to check
Definition at line 434 of file preferences.cpp.
 {
     //stop here when clearing the camera mode QComboBox
     if (i_name.isEmpty()) {
         return;
     }
     //gphoto2
     if (i_name == QStringLiteral("gphoto2")) {
         const auto message = tr("'%1' is missing%2")
                                  .arg(i_name, tr(": <a href='https://github.com/gonzalo/gphoto2-updater/'>Linux (gphoto2 updater)</a>"
                                                  "/<a href='https://brew.sh/'>macOS (Homebrew)</a>"));
         if (applicationAvailable(i_name, message)) {
             //add info about gphoto2
             m_ui->lblCameraModeInfo->setText(gphotoInfo(i_name));
         }
         return;
     }
     //Raspberry Pi Camera Module
     if (i_name == QStringLiteral("raspistill")) {
         const auto message = tr("'%1' is missing%2")
                                  .arg(i_name, tr(": <a href='https://www.raspberrypi.org/documentation/usage/camera/'>"
                                                  "Raspberry Pi Camera Module - enabling the camera</a>"));
         applicationAvailable(i_name, message);
         return;
     }
     //Other Applications
     const auto message = tr("'%1' is missing%2").arg(i_name, QLatin1String(""));
     applicationAvailable(i_name, message);
 }
References applicationAvailable(), gphotoInfo(), and m_ui.
Referenced by connectUi().
verifyPath
auto Preferences::verifyPath (const QString & i_path) private slot
Check if the path is useable.
Parameters
i_path QString directory which stores the photos
Returns
true: path is okay false: something wrong, show warning
Definition at line 315 of file preferences.cpp.
 {
     QFileInfo path(i_path);
     //check if path exists
     if (!path.exists()) {
         //create dir
         QDir dir(i_path);
         if (!dir.mkpath(QStringLiteral("."))) {
             QMessageBox::warning(this, tr("photo folder") , tr("The directory doesn't exist and also couldn't be created."));
             return false;
         }
     }
     //check if a directory
     if (!path.isDir()) {
         QMessageBox::warning(this, tr("photo folder") , tr("Please select a directory and not a file."));
         return false;
     }
     //check if readale and writable
     if (!path.isReadable() || !path.isWritable()) {
         QMessageBox::warning(this, tr("photo folder") , tr("Write and read rights are required. Please check the permission of the directory."));
         return false;
     }
     return true;
 }
Referenced by chooseDirectory(), and connectUi().
windowPosition()
void Preferences::windowPosition () private
Set the window position.
if the height of the Preference dialog is greater than the available screen height, start maximizing otherwise center the dialog
Definition at line 69 of file preferences.cpp.
 {
     const auto availableGeometry = QGuiApplication::primaryScreen()->availableGeometry();
     if (frameGeometry().height() > availableGeometry.height()) {
         //start maximized to be able to reach the dialog buttons
         showMaximized();
     } else {
         //enough space, center dialog
         setGeometry(QStyle::alignedRect(Qt::LeftToRight, Qt::AlignCenter, size(), availableGeometry));
     }
 }
Referenced by Preferences().
Member Data Documentation
COUNTDOWN_START_VALUE
constexpr int Preferences::COUNTDOWN_START_VALUE = 10 static constexpr private
Countdown start value (10 seconds)
Definition at line 165 of file preferences.h.
DEFAULT_COUNTDOWN_START_VALUE
constexpr int Preferences::DEFAULT_COUNTDOWN_START_VALUE = 3 static constexpr private
Default countdown start value (3 seconds)
Definition at line 168 of file preferences.h.
Referenced by restoreDefaultPreferences().
DEFAULT_INPUT_PIN
constexpr int Preferences::DEFAULT_INPUT_PIN = 5 static constexpr private
Default input PIN
Definition at line 171 of file preferences.h.
Referenced by restoreDefaultPreferences().
DEFAULT_OUTPUT_PIN
constexpr int Preferences::DEFAULT_OUTPUT_PIN = 0 static constexpr private
Default output PIN
Definition at line 174 of file preferences.h.
Referenced by restoreDefaultPreferences().
DEFAULT_QUERY_INTERVAL
constexpr int Preferences::DEFAULT_QUERY_INTERVAL = 10 static constexpr private
Default query interval
Definition at line 177 of file preferences.h.
Referenced by restoreDefaultPreferences().
DEFAULT_TIMEOUT
constexpr int Preferences::DEFAULT_TIMEOUT = 30 static constexpr private
Default time out (QProcess timed out)
Definition at line 180 of file preferences.h.
Referenced by restoreDefaultPreferences().
m_countdown
Countdown Preferences::m_countdown private
Countdown to "auto close dialog"
Definition at line 189 of file preferences.h.
Referenced by Preferences(), startFotoBox(), and stopCountdownMode().
m_settings
QSettings Preferences::m_settings private
Store and read settings (INI file)
Definition at line 186 of file preferences.h.
Referenced by loadPreferences(), and savePreferences().
m_ui
Ui::PreferencesDialog* Preferences::m_ui private
User Interface
Definition at line 183 of file preferences.h.
Referenced by chooseDirectory(), colorDialog(), connectUi(), loadPreferences(), Preferences(), restoreDefaultPreferences(), savePreferences(), setButtonIcons(), stopCountdownMode(), verifyApplication(), and ~Preferences().
The documentation for this class was generated from the following files:
preferences.h
preferences.cpp